apiVersion: v1
kind: Pod
metadata:
  name: titanml-pod
  labels:
    name: titanml-pod
spec:
  containers:
  - name: ubuntu
    image: mendeza/takeoff-mistral
    command: ["/bin/sh", "-c"]
    args:
      - echo starting;
        export TAKEOFF_MODEL_NAME={{TAKEOFF_MODEL_NAME}};
        export TAKEOFF_DEVICE={{TAKEOFF_DEVICE}};
        sh run.sh
    ports:
    - containerPort: {{API_PORT}}
      hostPort: {{API_PORT}}
    volumeMounts:
    - name: host-volume
      mountPath: /code/models/
    - name: host-volume2
      mountPath: /nvmefs1/
    resources:
      limits:
        rdma/rdma_shared_device_a: '1'
        rdma/rdma_shared_device_b: '3'
      requests:
          rdma/rdma_shared_device_a: '1'
          rdma/rdma_shared_device_b: '3'
  tolerations:
    - effect: NoSchedule
      key: accelerator
      operator: Equal
      value: NVIDIA-A100-SXM4-80GB
  volumes:
  - name: host-volume
    hostPath:
      path: {{HOST_VOLUME}}
  - name: host-volume2
    hostPath:
      path: {{HOST_VOLUME2}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: titanml-pod-svc
  name: titanml-pod-svc
spec:
  type: LoadBalancer
  ports:
  - nodePort: 31174
    port: {{API_PORT}}
    protocol: TCP
    targetPort: {{API_PORT}}
  selector:
    name: titanml-pod
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{API_HOST}}
